---
- name: Install PHP using dnf
  hosts: app_server
  become: yes
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ ssh_private_key_file }}"

  tasks:
    - name: Ensure PHP is installed
      dnf:
        name: php
        state: present

    - name: Install additional PHP packages
      dnf:
        name:
          - php-cli
          - php-common
          - php-fpm
          - php-mysqlnd
        state: present