---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Install boto python package
      ansible.builtin.pip:
        name:
          - botocore
          - boto3

    - name: Get SSH private key from S3
      aws_s3:
        bucket: ansible-test-kuriya
        object: ansible-test-kuriya.pem
        dest: "{{ key_name }}"
        mode: get
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_access_key }}"

    - name: Change permissions of the SSH private key
      ansible.builtin.file:
        path: "{{ key_name }}"
        mode: "{{ key_permissions }}"