---
- hosts: localhost
  gather_facts: no

  tasks:
    - name: Install boto python package
      ansible.builtin.pip:
        name:
          - botocore
          - boto3

    - name: Get SSH private key from S3
      aws_s3:
        bucket: ansible-test-kuriya
        object: ansible-test-kuriya.pem
        dest: "{{ key_name }}"
        mode: get
        access_key: "{{ aws_access_key }}"
        secret_key: "{{ aws_secret_access_key }}"

    - name: Change permissions of the SSH private key
      ansible.builtin.file:
        path: "{{ key_name }}"
        mode: "{{ key_permissions }}"

- name: Configure EC2 instance
  hosts: web_server
  become: yes
  gather_facts: yes
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ key_name }}"

  tasks:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd
        state: present

    - name: Start Apache HTTP Server
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: Install PHP using dnf
  hosts: app_server
  become: yes
  vars:
    ansible_user: ec2-user
    ansible_ssh_private_key_file: "{{ key_name }}"

  tasks:
    - name: Ensure PHP is installed
      dnf:
        name: php
        state: present

    - name: Install additional PHP packages
      dnf:
        name:
          - php-cli